apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
        - name: test1
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}