apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-app
  namespace: argocd   # the namespace where your ArgoCD is installed
spec:
  project: default
  source:
    repoURL: https://github.com/TehilaTheStudent/my-helm-charts.git
    targetRevision: HEAD   # or the version you want
    path: secret-chart
   
  destination:
    server: https://kubernetes.default.svc
    namespace: secret-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
