apiVersion: batch/v1
kind: Job
metadata:
  name: delete-job
  annotations:
    "helm.sh/hook": pre-delete
    # "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: crossplane-hooks-sa
      containers:
        - name: delete-job
          image: bitnami/kubectl:latest
          command: ["/bin/sh"]
          args:
            - -c
            - |
              echo "Deleting GitLab CRD resources..."
              
              # Delete all instances of each GitLab CRD (excluding providerconfig and providerconfigusage)
              kubectl delete accesstokens.groups.gitlab.crossplane.io --all --wait=true || echo "No accesstokens.groups found"
              kubectl delete accesstokens.projects.gitlab.crossplane.io --all --wait=true || echo "No accesstokens.projects found"
              kubectl delete approvalrules.projects.gitlab.crossplane.io --all --wait=true || echo "No approvalrules.projects found"
              kubectl delete deploykeys.projects.gitlab.crossplane.io --all --wait=true || echo "No deploykeys.projects found"
              kubectl delete deploytokens.groups.gitlab.crossplane.io --all --wait=true || echo "No deploytokens.groups found"
              kubectl delete deploytokens.projects.gitlab.crossplane.io --all --wait=true || echo "No deploytokens.projects found"
              kubectl delete groups.groups.gitlab.crossplane.io --all --wait=true || echo "No groups.groups found"
              kubectl delete hooks.projects.gitlab.crossplane.io --all --wait=true || echo "No hooks.projects found"
              kubectl delete members.groups.gitlab.crossplane.io --all --wait=true || echo "No members.groups found"
              kubectl delete members.projects.gitlab.crossplane.io --all --wait=true || echo "No members.projects found"
              kubectl delete pipelineschedules.projects.gitlab.crossplane.io --all --wait=true || echo "No pipelineschedules.projects found"
              kubectl delete projects.projects.gitlab.crossplane.io --all --wait=true || echo "No projects.projects found"
              kubectl delete runners.groups.gitlab.crossplane.io --all --wait=true || echo "No runners.groups found"
              kubectl delete runners.projects.gitlab.crossplane.io --all --wait=true || echo "No runners.projects found"
              kubectl delete samlgrouplinks.groups.gitlab.crossplane.io --all --wait=true || echo "No samlgrouplinks.groups found"
              kubectl delete storeconfigs.gitlab.crossplane.io --all --wait=true || echo "No storeconfigs found"
              kubectl delete variables.groups.gitlab.crossplane.io --all --wait=true || echo "No variables.groups found"
              kubectl delete variables.projects.gitlab.crossplane.io --all --wait=true || echo "No variables.projects found"
              
              echo "Waiting for all resources to be deleted..."
              sleep 10
              
              echo "Deleting provider..."
              
              # Delete the provider
              if kubectl get providers provider-gitlab >/dev/null 2>&1; then
                echo "Deleting provider provider-gitlab..."
                kubectl delete providers provider-gitlab --cascade=foreground
                echo "Provider deleted successfully"
              else
                echo "Provider provider-gitlab not found, nothing to delete"
              fi
      restartPolicy: Never
  backoffLimit: 1
