# # # kind-registry.yaml
# # kind: Cluster
# # apiVersion: kind.x-k8s.io/v1alpha4
# # nodes:
# #   - role: control-plane
# # # containerdConfigPatches:
# # # - |-
# # #   [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
# # #     endpoint = ["http://localhost:5000"]
# # containerdConfigPatches:
# # - |-
# #   [plugins."io.containerd.grpc.v1.cri".registry.mirrors."51.20.178.23:5000"]
# #     endpoint = ["http://51.20.178.23:5000"]
# # # kind-config.yaml

# # kind: Cluster
# # apiVersion: kind.x-k8s.io/v1alpha4
# # nodes:
# #   - role: control-plane
# # containerdConfigPatches:
# # - |-
# #   [plugins."io.containerd.grpc.v1.cri".registry.mirrors."kind-registry:5000"]
# #     endpoint = ["http://kind-registry:5000"]
# kind: Cluster
# apiVersion: kind.x-k8s.io/v1alpha4
# nodes:
# - role: control-plane
#   extraMounts:
#   - hostPath: ./certs/domain.crt
#     containerPath: /etc/containerd/certs.d/kind-registry:5000/ca.crt
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: ./certs/domain.crt
    containerPath: '/etc/containerd/certs.d/kind-registry:5000/ca.crt'
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.configs."kind-registry:5000".tls]
    ca_file = "/etc/containerd/certs.d/kind-registry:5000/ca.crt"
    insecure_skip_verify = false